services:
  blog:
    container_name: blog
    build: .
    ports:
      - "3004:3004"
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3004"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
